# Generated by Django 4.2.5 on 2023-11-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_img/', verbose_name='Излбражение')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изобажения товаров',
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(max_length=70, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Имя товара')),
                ('description', models.TextField(verbose_name='Описние')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('alt_price', models.IntegerField(default=0, verbose_name='Цена')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Скидка в процентах')),
                ('besteller', models.BooleanField(default=False, verbose_name='Бестселлер')),
                ('new_product', models.BooleanField(default=True, verbose_name='Новый товар')),
                ('sale_products', models.BooleanField(default=False, verbose_name='Скидка на товар')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor_product', to='shoopelectonic.categories', verbose_name='Категория')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoopelectonic.imageproduct', verbose_name='Изображение')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoopelectonic.manufacturers', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
